apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: changelog
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
        - image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --use-git-tag-only --tag
        - image: ghcr.io/jenkins-x/jx:3.2.103
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: get-jx-prerelease-state
          resources: {}
          script: |
            #!/bin/sh
            ./.lighthouse/jenkins-x/release/get-jx-prerelease-state.sh
        - image: gcr.io/jenkinsxio/jx-scm:0.0.7
          name: release-jx-cli
          resources: {}
          env:
          - name: GOPATH
            value: /workspace
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: tekton-git
                key: password
          script: |
            #!/bin/sh
            export JX_VERSION=$(grep 'version: ' packages/jx.yml | awk '{ print $2}')
            export LH_VERSION=$(grep 'version: ' charts/jx3/lighthouse/defaults.yaml | awk '{ print $2}')
            echo "using versions JX: ${JX_VERSION} lighthouse: ${LH_VERSION}"
            jx scm release update --owner jenkins-x --name jx --tag v$JX_VERSION --prerelease=false --kind github --server https://github.com --token $GITHUB_TOKEN
            jx scm release update --owner jenkins-x --name lighthouse --tag v$LH_VERSION --prerelease=false --kind github --server https://github.com --token $GITHUB_TOKEN
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.11
          name: changelog
          resources: {}
          script: |
            #!/bin/sh
            source .jx/variables.sh
            jx changelog create --verbose --version ${VERSION} --rev v${VERSION}
        - image: ghcr.io/jenkins-x/jx:3.2.103
          name: promote-vs
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            ./.lighthouse/jenkins-x/release/promote-vs.sh
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
