apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: eks
    context: "eks"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| eks),?(s+|$)
    rerun_command: /test eks
    source: "pullrequest-eks.yaml"
  - name: ghe
    context: "ghe"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| ghe),?(s+|$)
    rerun_command: /test ghe
    source: "pullrequest-ghe.yaml"
  - name: gsm
    context: "gsm"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| gsm),?(s+|$)
    rerun_command: /test gsm
    source: "pullrequest.yaml"
  - name: tls
    context: "tls"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| tls),?(s+|$)
    rerun_command: /test tls
    source: "pullrequest.yaml"
  - name: vault
    context: "vault"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| vault),?(s+|$)
    rerun_command: /test vault
    source: "pullrequest.yaml"
  - name: kube
    context: "kube"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| kube),?(s+|$)
    rerun_command: /test kube
    source: "pullrequest.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - main
    - master